CREATE TABLE Bookings (
    bookingID VARCHAR(100) PRIMARY KEY,
    userID VARCHAR(100),
    tourID VARCHAR(100),
    FOREIGN KEY (userID) REFERENCES Users(userID),
    FOREIGN KEY (tourID) REFERENCES Tours(tourID),
    bookingDate DATETIME DEFAULT GETDATE()
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK__Bookings__tourID__531856C7')
BEGIN
    ALTER TABLE Bookings
    DROP CONSTRAINT FK__Bookings__tourID__531856C7;
END;

ALTER TABLE Bookings
ADD CONSTRAINT FK__Bookings__tourID__531856C7
FOREIGN KEY (tourID)
REFERENCES Tours(tourID)
ON DELETE CASCADE
ON UPDATE CASCADE;

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME = 'FK__Bookings__userID__5224328E')
BEGIN
    ALTER TABLE Bookings
    DROP CONSTRAINT FK__Bookings__userID__5224328E;
END;

ALTER TABLE Bookings
ADD CONSTRAINT FK__Bookings__userID__5224328E
FOREIGN KEY (userID)
REFERENCES Users(userID)
ON DELETE CASCADE
ON UPDATE CASCADE;




-- ALTER TABLE Bookings 
-- ADD COLUMN tourID ON DELETE CASCADE ON UPDATE CASCADE



SELECT * FROM Bookings

DROP TABLE Bookings

-- SELECT * FROM Bookings WHERE tourID NOT IN (SELECT tourID FROM Tours);
