###
POST http://localhost:4500/users/register/
Content-Type: application/json

{
    "fullName": "Isaac Kilimo",
    "email": "isaackilimok2@gmail.com",
    "password": "12345678@Ik"
}


### login 
POST http://localhost:4500/users/login/
Content-Type: application/json

{
   "email": "isaackilimok2@gmail.com",
   "password": "12345678@Ik" 
}

### fetching all users
GET http://localhost:4500/users/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmOTlhYzVlZS1jOWRhLTRmN2MtYjcxOS02MmFlMzZmNWI2YjUiLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDAyOTYwODIsImV4cCI6MTcwMDQ2ODg4Mn0.jK91lrBPSp7dR9tzAWmAqFJ5-hw2CZiBMAqz0C6MB8g


###update user
POST http://localhost:4500/users/updateUser/18b1d912-6bee-4648-b22d-b64ad7ac5e63/
Content-Type: application/json

{
    "fullName": "New meshack",
    "email": "meshack42@gmail.com"
}

### fetching single user
GET http://localhost:4500/users/singleUser/f99ac5ee-c9da-4f7c-b719-62ae36f5b6b5/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmOTlhYzVlZS1jOWRhLTRmN2MtYjcxOS02MmFlMzZmNWI2YjUiLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDAyOTYwODIsImV4cCI6MTcwMDQ2ODg4Mn0.jK91lrBPSp7dR9tzAWmAqFJ5-hw2CZiBMAqz0C6MB8g


### fetching user
GET http://localhost:4500/users/details/f99ac5ee-c9da-4f7c-b719-62ae36f5b6b5/
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmOTlhYzVlZS1jOWRhLTRmN2MtYjcxOS02MmFlMzZmNWI2YjUiLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDAyOTYwODIsImV4cCI6MTcwMDQ2ODg4Mn0.jK91lrBPSp7dR9tzAWmAqFJ5-hw2CZiBMAqz0C6MB8g


### checking user details
GET http://localhost:4500/users/checkUserDetails/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJmOTlhYzVlZS1jOWRhLTRmN2MtYjcxOS02MmFlMzZmNWI2YjUiLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsImVtYWlsIjoiaXNhYWNraWxpbW9rMkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MDAyOTYwODIsImV4cCI6MTcwMDQ2ODg4Mn0.jK91lrBPSp7dR9tzAWmAqFJ5-hw2CZiBMAqz0C6MB8g


#### deleting user
DELETE http://localhost:4500/users/delete/af604f8a-312d-4eef-b42d-d6e2ca7f11e8/

###### creating new tour
POST http://localhost:4500/tours/create
Content-Type: application/json

{
    "name": "React project",
    "description": "to be ready by this weekend",
    "destination": "Mt Elgon",
    "type": "to be ready by this weekend",
    "price": "11500",
    "startDate": "12/13/2023",
    "endDate": "12/13/2023",
    "duration": "5"
}

### fetching all tours

GET http://localhost:4500/tours/all


### fetching one tour
GET http://localhost:4500/tours/single/352ba489-4c63-4abd-8165-e573a528889e/


###### Updating tour
POST http://localhost:4500/tours/update/39f7e435-6b1f-401a-8e7c-56c26e2a2fb5/
Content-Type: application/json

{
    "name": "Daring the waters",
    "description": "We will have swimming activities",
    "destination": "londiani and malindi",
    "price": 7000,
    "type": "culture",
    "startDate": "2023-11-10",
    "endDate": "2023-11-22",
    "duration": "7"
  }

###### book a tour
POST http://localhost:4500/tours/book/
Content-Type: application/json

{
    "userID": "e89cd53c-df5e-4ed4-a98a-9db4c7f9ced6",
    "tourID": "3d5d6c71-77c8-49b2-8f8e-38f0b5a79fec"

}

### fetching booked tour
GET http://localhost:4500/tours/bookedTours/e89cd53c-df5e-4ed4-a98a-9db4c7f9ced6/


# Deleting a project
###
DELETE http://localhost:4500/tours/c022d8bb-3443-4e12-b0a3-a62db6e53423/


### create reviews
POST http://localhost:4500/reviews/create/
Content-Type: application/json

{
    "userID": "960a0af1-c8cf-4dab-a16e-21bf33be0f28",
    "tourID": "329e9380-e68c-4a82-8625-7d4f694617c4",
    "comment": "It was so amazing,I enjoyed",
    "rating": "5"
}

### fetching all reviews
GET http://localhost:4500/reviews/all/


### fetching all reviews
GET http://localhost:4500/reviews/userReview/960a0af1-c8cf-4dab-a16e-21bf33be0f28/e89cd53c-df5e-4ed4-a98a-9db4c7f9ced6/


